server:
  port: 8880

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8761/eureka/
  instance:
    hostname: eureka-service

spring:
  cloud:
    gateway:
      discoveryClient:
        enabled: true
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: false
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: listRepair
          uri: lb://listRepair
          predicates:
            - Path=/listRepair/**
        - id: reparation
          uri: lb://reparation
          predicates:
            - Path=/repairs/**
        - id: repair_list_repair
          uri: lb://reparation
          predicates:
            - Path=/repair_list_repair/**
        - id: vehicle
          uri: lb://vehicle
          predicates:
            - Path=/vehicles/**
        - id: reports
          uri: lb://reports
          predicates:
            - Path=/reports/**
